In [21]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(
    "data2_3_2.txt",
    sep=',',
    parse_dates={'birthday': [0, 1, 2]},
    skiprows=2,
    skipfooter=2,
    comment='#',
    thousands='&',
    engine='python'
)
print(df)

    birthday gender name  income
0 2019-03-07      男   张三    6000
1 2019-02-01      女   王玲    8000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   birthday  2 non-null      datetime64[ns]
 1   gender    2 non-null      object
 2   name      2 non-null      object
 3   income    2 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 192.0+ bytes

In [6]:
df.head()

    birthday gender name  income
0 2019-03-07      男   张三    6000
1 2019-02-01      女   王玲    8000

In [7]:
df.tail()

    birthday gender name  income
0 2019-03-07      男   张三    6000
1 2019-02-01      女   王玲    8000

In [24]:
a = pd.read_excel("excel1.xlsx", usecols=range(1, 4))
b = a.values  # 提取其中的数据
c = a.describe()  # 对数据进行统计描述，返回数量，均值，标准差，最大最小值，25%、50%、75%分位数
print(b)
c  # 只能这样输出一行

[[235.83  324.03  478.32 ]
 [236.27  325.63  515.45 ]
 [238.05  328.08  517.09 ]
 [235.9       nan 514.89 ]
 [236.76  268.82      nan]
 [    nan 404.04  486.09 ]
 [237.41  391.26  516.23 ]
 [238.65  380.81      nan]
 [237.61  388.02  435.35 ]
 [238.03  206.43  487.675]]

              用户A         用户B         用户C
count    9.000000    9.000000    8.000000
mean   237.167778  335.235556  493.886875
std      1.021161   65.198685   28.565643
min    235.830000  206.430000  435.350000
25%    236.270000  324.030000  484.147500
50%    237.410000  328.080000  501.282500
75%    238.030000  388.020000  515.645000
max    238.650000  404.040000  517.090000

In [26]:
# 生成 DataFrame 类型数据
d = pd.DataFrame(b, index=np.arange(1, 11),
                 columns=["用户A", "用户B", "用户C"])
f = pd.ExcelWriter('excel2.xlsx')  # 创建文件对象
d.to_excel(f, "sheet1")  # 把 d 写入Excel文件中
d.to_excel(f, "sheet2")  # 把 d 再写入另一个表单中
f.close()  # 高版本 pandas 没有 save() 方法

In [27]:
# 3.数据子集的获取
a = pd.read_excel("excel1.xlsx", usecols=range(1, 4))
b1 = a.iloc[np.arange(6), [0, 1]]  # 通过标号筛选数据
b2 = a.loc[np.arange(6), ["用户A", "用户B"]]  # 通过标签筛选数据
print(b1, '\n', b2)

      用户A     用户B
0  235.83  324.03
1  236.27  325.63
2  238.05  328.08
3  235.90     NaN
4  236.76  268.82
5     NaN  404.04
       用户A     用户B
0  235.83  324.03
1  236.27  325.63
2  238.05  328.08
3  235.90     NaN
4  236.76  268.82
5     NaN  404.04