# 1. 使用适当的数据类型

1. Pandas 默认的数值类型是 int64 和 float64，但对于大部分数据，这可能会浪费内存。可以使用更小的类型，如 int8, int16, float32 等。

方法	说明
`astype()`	用于转换列的数据类型
`downcast`	将数据类型降级，例如将 int64 降级为 int32 或 int16

2. 对字符数据使用 `category` 类型

对于具有重复值的字符串列，可以使用 `category` 类型来减少内存消耗。category 类型在内存中存储的是整数索引，而不是字符串本身。

In [2]:
import pandas as pd

# 示例数据
df = pd.DataFrame({'A': [100, 200, 300, 400], 'B': [1000, 2000, 3000, 4000]})
display(df)
# 将列数据类型转换为较小的数据类型
df['A'] = df['A'].astype('int16')
df['B'] = df['B'].astype('int32')
display(df)
print(df.dtypes)

     A     B
0  100  1000
1  200  2000
2  300  3000
3  400  4000

     A     B
0  100  1000
1  200  2000
2  300  3000
3  400  4000

A    int16
B    int32
dtype: object

In [3]:
# 示例数据
df = pd.DataFrame({'Category': ['A', 'B', 'A', 'C', 'B', 'A']})
display(df)
# 使用 category 类型
df['Category'] = df['Category'].astype('category')
display(df)
print(df.dtypes)

  Category
0        A
1        B
2        A
3        C
4        B
5        A

  Category
0        A
1        B
2        A
3        C
4        B
5        A

Category    category
dtype: object

# 2. 向量化操作

Pandas 的最大优势之一就是其能够利用向量化操作进行快速的批量运算。在 Pandas 中，尽量避免使用 Python 的原生循环，应该使用 Pandas 内置的函数，这样可以利用底层的优化进行快速计算。

# 3. 分块加载大数据集

当数据集过大时，加载整个数据集会占用大量内存，甚至导致内存溢出。此时，可以通过分块读取数据来减小内存压力。

Pandas 提供了 `chunksize` 参数，允许在读取 CSV 或 Excel 文件时分块加载数据。

`Dask` 和 `Vaex` 是两个能够处理比内存更大的数据集的库。它们与 Pandas 兼容，支持多线程和分布式计算，可以有效地处理非常大的数据集。