In [83]:
import pandas as pd

下载 titanic 数据，  
默认在C:\Users\yuanx\AppData\Local\seaborn\seaborn\Cache

In [ ]:
import seaborn as sns
titanic = sns.load_dataset("titanic")

# 导入导出数据

导入csv数据

In [84]:
df = pd.read_csv("titanic.csv")
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

将csv文件导出为xlsx文件，并去掉序号

导入excel数据（read_excel）

In [85]:
df.to_excel('titanic.xlsx', index=False)
data = pd.read_excel("titanic.xlsx")

# 浏览数据

导入excel数据

1.查看表格，输入表格对象名，在jupyter中不用print语句

In [86]:
data

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

2.数据量很大，查看表格前五行

In [16]:
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

3.输出表格的行数和列数，注意：shape后面没有括号

In [8]:
data.shape

(891, 15)

4.看表格列的信息，包括行数（索引也会显示），列的总数，各列的非空值个数（可能有缺失值），各列的数据类型，并统计有多少列是什么类型，显示的是内存中的数据结构占用的内存大小，可能会有额外的开销，例如用于索引、元数据等。

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

5.查看表格的基本统计量，包括各列的元素数量，各列均值，标准差，最大最小值，25%、50%（中位数）、75%分位数

In [12]:
data.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

# 行列过滤

语法 dataframe[dataframe['col'] + 条件]

下面是单个条件，注意不要漏了dataframe和中括号

注意：条件在df[]的括号外面，即df[''] + 条件

In [20]:
df[df['age'] > 70]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

下面是多个条件

dataframe[(dataframe['col'] + 条件) 逻辑运算符 (dataframe['col' + 条件])]  

位运算符（|（按位或，多个条件中只要满足其中一个）&（按位与，多个条件同时满足））连接的两个条件用小括号括起来，外面用中括号

按位与 多个条件中只要满足其中一个

In [27]:
data[(data['age'] > 20) | (data['age'] < 40)]  # 714行

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

按位或，多个条件同时满足

In [26]:
data[(data['age'] > 20) & (data['age'] < 40)]  # 372行

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

筛选行和列

df[(df['col']+条件)][['col', 'col']]

行筛选一个条件也要加小括号，列筛选 筛选多列时两个中括号，筛选一列时一个中括号，当然，也可以先筛选行，后筛选列，通常只筛选行

In [29]:
data[(data['age'] > 70)]['age']

96     71.0
116    70.5
493    71.0
630    80.0
851    74.0
Name: age, dtype: float64

In [30]:
data[(data['age'] > 70)][['age', 'survived']]

      age  survived
96   71.0         0
116  70.5         0
493  71.0         0
630  80.0         1
851  74.0         0

筛选列

In [31]:
data['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

只查看一列的前五行(实际一个中括号展示应该没有列名)，返回的是Series(5,)

In [32]:
data['age'].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

只查看一列的前五行(实际两个中括号展示有列名)，返回的是dataframe(5,1)（数据框）

In [33]:
data[['age']].head()

    age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0

同样的，也可以筛选两列

此时，要使用两个中括号

In [35]:
data[['age', 'survived']]

      age  survived
0    22.0         0
1    38.0         1
2    26.0         1
3    35.0         1
4    35.0         0
..    ...       ...
886  27.0         0
887  19.0         1
888   NaN         0
889  26.0         1
890  32.0         0

[891 rows x 2 columns]

同时筛选行和列，建议使用 loc （location）方法

df.loc[(df['col']+条件 位运算符 (df['clo']+条件)), ['col', 'col']]

筛选多个参数是加中括号（返回DataFrame类型），1个参数时默认返回Series类型，要返回DataFrame类型加个中括号

In [40]:
data.loc[(data['age'] > 70) & (data['survived'] > 0), ['survived', 'age']]

     survived   age
630         1  80.0

# 排序

df.sort_values(by = 'col', ascending = True/False).dropna()

是用sort_values方法进行升序(默认)排序（降序ascending=False）(ascending上升)

dropna()可以去掉空值(只要该行有空值，就去掉该行，去掉行不只是按这一列的空值去除，包括其他列的空值)

In [41]:
data.sort_values(by = 'age')  # 891行

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [43]:
data.sort_values(by = 'age', ascending = False).dropna()  # 182行

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.00,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
96,0,1,male,71.00,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
745,0,1,male,70.00,1,1,71.0000,S,First,man,True,B,Southampton,no,False
54,0,1,male,65.00,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
456,0,1,male,65.00,0,0,26.5500,S,First,man,True,E,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,0,3,female,2.00,0,1,10.4625,S,Third,child,False,G,Southampton,no,False
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
340,1,2,male,2.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
183,1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False

# 新增列

df['新增列的列名'] = df['col'] + 条件 ————— 返回 bool 类型数据

df['新增列的列名'] = df['col1'] + df['col2'] + num ———— 返回类型根据参与运算的列的类型确定

列与列间进行计算合并

In [46]:
# 新增一列看是否已成年
data['is child'] = data['age'] > 18
data.info()  # 可以看到多了一列 is child 为布尔类型

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
 15  is child     891 non-null    bool
dtypes: bool(3), float64(2), int64(4), object(7)
memory usage: 93.2+ KB

In [47]:
data['familysize'] = df['sibsp'] + df['parch'] + 1
data.info()  # 可以看到，返回int类型

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
 15  is child     891 non-null    bool
 16  familysize   891 non-null    int64
dtypes: bool(3), float64(2), int64(5), object(7)
memory usage: 100.2+ KB

# pandas 最重要的应用：数据聚合

pivot_basic = df.pivot_table(
    
    values='sales',      # 需要聚合的列
    
    index='month',       # 行：按月份分组
    
    columns='category',  # 列：按类别分组
    
    aggfunc='sum',       # 聚合函数：求和（aggregate 总数的）
    
    fill_value=0         # 填充缺失值为0
)

参数	                        功能	                                        示例值与效果

values	        指定需要聚合的列名（可选，默认所有数值列）	            'sales'：只聚合销售额列

index	        行方向的分组依据（类似 groupby 的 by 参数）	        'month'：按月份分组作为行索引；['year', 'month']：多级行索引

columns	        列方向的分组依据	                                'category'：按类别分组作为列索引

aggfunc	        聚合函数（默认平均值）	                            'sum'：求和；['sum', 'mean']：同时应用多个函数；{'sales': 'sum'}：自定义列的聚合函数

fill_value	    填充结果中的缺失值	                                    0：将 NaN 填充为 0

margins	        是否添加总计行 / 列	                            True：在结果边缘添加 All 行 / 列

margins_name	总计行 / 列的名称	                                '总计'：将默认的 All 改为 总计

dropna	        是否排除全为 NaN 的列	                                True：默认排除

observed	对分类变量是否只显示实际存在的组（类似 groupby）	        False：显示所有可能的分类组合（即使无数据）

df.groupby('聚合根据的列')[['根据该列进行计算']].func()

groupby方法进行聚合，后面的func()指可以使用其他的函数，一个中括号返回Series，两个中括号返回DataFrame

In [48]:
data.groupby('sex')['survived'].sum()  # survived 为 bool 类型，我们直接相加

sex
female    233
male      109
Name: survived, dtype: int64

In [49]:
data.groupby('sex')[['survived']].sum()

        survived
sex
female       233
male         109

根据多个列进行聚合

df.groupby()

df.groupby(['根据聚合的列1', '根据聚合的列2'])[['该列进行聚合']].reset_index（根据两列，故传入列表['根据聚合的列1', '根据聚合的列2']）

根据聚合的列1 和 根据聚合的列2 会变成新数据框的 index，所以会有空行，如果要按正常表格查看，要使用reset_index方法

In [50]:
data.groupby(['sex', 'class'])[['survived']].sum()

               survived
sex    class
female First         91
       Second        70
       Third         72
male   First         45
       Second        17
       Third         47

In [51]:
data.groupby(['sex', 'class'])[['survived']].sum().reset_index()

      sex   class  survived
0  female   First        91
1  female  Second        70
2  female   Third        72
3    male   First        45
4    male  Second        17
5    male   Third        47

In [52]:
# 根据 survived 对新表格进行 降序 （ascending=False）排列
data.groupby(['sex', 'class'])[['survived']].sum().reset_index().sort_values(by='survived', ascending=False)

      sex   class  survived
0  female   First        91
2  female   Third        72
1  female  Second        70
5    male   Third        47
3    male   First        45
4    male  Second        17

In [60]:
# 根据 sex 和 class 计算 age 的均值
# mean() 和 reset_index() 顺序不能变，先求均值，再对新的表格进行重置索引(这些函数的排序 按照你想对数据进行什么处理 排序)
data.groupby(['sex', 'class'])[['age']].mean().reset_index().sort_values(by='age', ascending=False)

      sex   class        age
3    male   First  41.281386
0  female   First  34.611765
4    male  Second  30.740707
1  female  Second  28.722973
5    male   Third  26.507589
2  female   Third  21.750000

# pandas 重要应用：数据透视

df.pivot_table(

    values=None,      # 需要聚合的列名
    
    index=None,       # 行索引（分组依据）
    
    columns=None,     # 列索引（分组依据）
    
    aggfunc='mean',   # 聚合函数（默认平均值）
    
    fill_value=None,  # 填充缺失值
    
    margins=False     # 是否添加总计行/列
)

(pivot_table数据透视表)

aggfunc（aggregation function聚合函数）

统计类：sum（求和）、mean（均值）、median（中位数）、min（最小值）、max（最大值）、std（标准差）、var（方差）

计数类：count（计数）、nunique（唯一值计数）

自定义函数：如 lambda x: x.quantile(0.75)（计算 75% 分位数）

In [62]:
data.pivot_table(
    index = 'sex', 
    columns = 'class', 
    values = 'survived', 
    aggfunc = 'sum'
)

class   First  Second  Third
sex
female     91      70     72
male       45      17     47

# pandas 重要应用：表格关联

result = pd.merge(
    
    left, 
    
    right, 
    
    how='inner', 
    
    on=None, 
    
    left_on=None, 
    
    right_on=None,
                  
    left_index=False, 
        
    right_index=False, 
        
    sort=False,
                  
    suffixes=('_x', '_y'), 
       
    copy=True, 
    
    indicator=False,
                  
    validate=None
)

参数说明
1. `left` 和 `right` ：必选参数，分别是要合并的两个 DataFrame 对象

2. `how`：指定合并的方式，默认为 'inner'。可选值有：

`inner`：内连接，只保留两个表中键值都存在的行，类似于 SQL 中的 INNER JOIN  
`outer`：外连接，保留两个表中的所有行，缺失值用 NaN 填充，类似于 SQL 中的 FULL OUTER JOIN  
`left`：左连接，保留左表中的所有行，右表中不存在匹配键值的行用 NaN 填充，类似于 SQL 中的 LEFT JOIN  
`right`：右连接，保留右表中的所有行，左表中不存在匹配键值的行用 NaN 填充，类似于 SQL 中的 RIGHT JOIN

3. `on`：指定用于合并的列名，该列必须在两个 DataFrame 中同时存在。如果两个 DataFrame 中列名不同，不能使用该参数，而应使用 left_on 和 right_on

4. `left_on` 和 `right_on`：分别指定左表和右表中用于合并的列名。当两个 DataFrame 中列名不同但表示相同含义时使用

5. `left_index` 和 `right_index`：如果为 True，则使用左表或右表的索引作为连接键。可以同时设置为 True 进行索引合并

6. `sort`：默认为 False，表示是否按照字典顺序对合并后的 DataFrame 进行排序

7. `suffixes`：当两个 DataFrame 中有相同列名时，用于区分的后缀，默认为 ('_x', '_y')

8. `copy`：默认为 True，表示是否复制数据

9. `indicator`：如果设置为 True 或字符串，会在结果中添加一列，指示每行数据的来源

10. `validate`：用于指定合并的约束条件，如 'one_to_one'（一对一连接）、'one_to_many'（一对多连接）等

计算男性、女性的存活率

In [70]:
# 计算存活的人数
data_survived = data.groupby('sex')['survived'].sum().reset_index()
data_survived

      sex  survived
0  female       233
1    male       109

In [72]:
# 计算存活的总人数（count 计数不论是否存活）
data_total = data.groupby('sex')['survived'].count().reset_index()
data_total

      sex  survived
0  female       314
1    male       577

In [77]:
# 对两个表进行关联，根据 sex 关联
data_merge = pd.merge(data_survived, data_total, on='sex')
data_merge

      sex  survived_x  survived_y
0  female         233         314
1    male         109         577

rename()方法

DataFrame.rename(mapper=None, index=None, columns=None, axis=None, copy=True, inplace=False)


常用参数说明

mapper：用于指定映射关系，可以是字典或函数，axis和index或columns参数二选一使用，若同时指定，优先使用index或columns

当axis=0（即针对行索引操作）时，mapper是行索引的映射；

当axis=1（即针对列操作）时，mapper是列名的射

index：专门用于重命名行索引，值为字典或函数，字典形式为{原索引名: 新索引名}

columns：专门用于重命名列，值为字典或函数，字典形式为{原列名: 新列名}

axis：指定重命名操作的轴，取值为0（或'index'）表示对行索引操作，取值为1（或'columns'）表示对列进行操作

copy：默认为True，表示是否复制数据。如果设置为False，在某些情况下可能会返回一个视图而不是副本

inplace：默认为False，表示是否在原DataFrame上进行修改

若设置为True，则直接修改原DataFrame，方法返回None；

若设置为False，则返回一个修改后的新DataFrame，原DataFrame保持不变

In [79]:
# survivel_x 和 survivel_y 不好看，修改列名
data_merge.rename(
    columns = {'survived_x': 'survived', 'survived_y': 'total'}, 
    inplace = True  # 在原数据框上修改
)
data_merge

      sex  survived  total
0  female       233    314
1    male       109    577

In [81]:
# 增加新行存活率
data_merge['survived_percent'] = data_merge['survived'] / data_merge['total']
data_merge

      sex  survived  total  survived_percent
0  female       233    314          0.742038
1    male       109    577          0.188908