# 1. 了解 Pandas

### (1) Pandas 应用

Pandas 可以从各种文件格式比如 CSV、JSON、SQL、Microsoft Excel 导入数据。

Pandas 可以对各种数据进行运算操作，比如归并、再成形、选择，还有数据清洗和数据加工特征。

Pandas 广泛应用在学术、金融、统计学等各个数据分析领域。

### (2) Pandas 功能

数据清洗：处理缺失数据、重复数据等。  
数据转换：改变数据的形状、结构或格式。  
数据分析：进行统计分析、聚合、分组等。  
数据可视化：通过整合 Matplotlib 和 Seaborn 等库，可以进行数据可视化。

### (3) Pandas 数据结构

`Series` 是一种类似于一维数组的对象，它由一组数据（各种 Numpy 数据类型）以及一组与之相关的数据标签（即索引）组成。(**index+1列column**)

`DataFrame` 是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔型值）。DataFrame 既有行索引也有列索引，它可以被看做由 Series 组成的字典（共同用一个索引）。(**index+多列column（key(列名)+value(列的内容)）**)

### （4）Pandas 特点

**高效的数据结构**：

`Series`：一维数据结构，类似于列表（`List`），但拥有更强的功能，支持索引。  
`DataFrame`：二维数据结构，类似于表格或数据库中的数据表，行和列都具有标签（索引）。

**数据清洗与预处理**：

`Pandas` 提供了丰富的函数来处理缺失值、重复数据、数据类型转换、字符串操作等，帮助用户轻松清理和转换数据。

**数据操作与分析**：

支持高效的数据选择、筛选、切片，按条件提取数据、合并、连接多个数据集、数据分组、汇总统计等操作。  
可以进行复杂的数据变换，如数据透视表、交叉表、时间序列分析等。

**数据读取与导出**：

支持从各种格式的数据源读取数据，如 `CSV、Excel、JSON、SQL` 数据库等。  
也可以将处理后的数据导出为不同格式，如 `CSV、Excel` 等。

**数据可视化**：

通过与 `Matplotlib` 和其他可视化工具的集成，`Pandas` 可以快速生成折线图、柱状图、散点图等常见图表。

**时间序列分析**：

支持强大的时间序列处理功能，包括日期的解析、重采样、时区转换等。

**性能与优化**：

`Pandas` 优化了大规模数据处理，提供高效的向量化操作，避免了使用 Python 循环处理数据的低效。  
还支持一些内存优化技术，比如使用 `category` 类型处理重复的数据。

### （5）Pandas 应用

金融领域：金融机构使用 Pandas 来处理和分析股票市场数据、财务数据、交易数据等。Pandas 的灵活性和高效性使得金融分析师能够快速进行数据清洗、统计分析、建模等工作。

科学研究：科学研究领域经常涉及大量的实验数据、观测数据等，Pandas 提供了强大的工具来处理和分析这些数据，例如天文学、生物学、地球科学等领域。

企业数据分析：各种企业和组织都需要对业务数据进行分析，以支持决策和战略规划。Pandas 提供了处理和分析企业数据的功能，包括销售数据、客户数据、运营数据等。

社交媒体分析：社交媒体平台产生的海量数据需要进行分析来了解用户行为、趋势和情感倾向。Pandas 可以帮助分析师处理和分析社交媒体数据，进行用户行为分析、情感分析等。

医疗保健：医疗保健领域需要处理和分析大量的医疗数据，包括患者数据、临床试验数据、医疗图像数据等。Pandas 提供了处理和分析这些数据的工具，支持医疗研究和临床决策。

教育研究：教育领域可以利用 Pandas 来处理学生表现数据、教学评估数据、课程数据等，从而进行教育研究和改进教学质量。

市场营销：市场营销专业人员可以使用 Pandas 分析市场数据、客户数据、广告数据等，以制定营销策略和优化市场活动效果。

In [4]:
import pandas as pd

data = {'Name': ['Google', 'Twitter', 'Facebook'], 'Age': [20, 25, 30]}
df = pd.DataFrame(data)

display(df)
print(df)

       Name  Age
0    Google   20
1   Twitter   25
2  Facebook   30

       Name  Age
0    Google   20
1   Twitter   25
2  Facebook   30

In [6]:
import pandas as pd
import numpy as np

data = np.array(['Google', 'Twitter', 'Facebook'])

df = pd.Series(data)

df

0      Google
1     Twitter
2    Facebook
dtype: object

In [7]:
# DataFrame 可以看作 Series 的和
import pandas as pd

series_apple = pd.Series([1, 3, 7, 4])
series_orange = pd.Series([2, 6, 3, 5])

df = pd.DataFrame({'apple': series_apple, 'orange': series_orange})  # 用字典合并

df

   apple  orange
0      1       2
1      3       6
2      7       3
3      4       5

# 2. Pandas 数据结构 -- Series

Series类似一维数组，具有数据与索引。

Series 可以储存任何数据类型(int, float, string), 并通过标签(索引)来访问元素。

### `Series` 特点

**一维数组**：Series 中的每个元素都有一个对应的索引值。

**索引**： 每个数据元素都可以通过标签（索引）来访问，默认情况下索引是从 0 开始的整数，但你也可以自定义索引。

**数据类型**： Series 可以容纳不同数据类型的元素，包括整数、浮点数、字符串、Python 对象等。

**大小不变性**：Series 的大小在创建后是不变的，但可以通过某些操作（如 `append` 或 `delete`）来改变。

**操作**：Series 支持各种操作，如数学运算、统计分析、字符串处理等。

**缺失数据**：Series 可以包含缺失数据，Pandas 使用`NaN`（Not a Number）来表示缺失或无值。

**自动对齐**：当对多个 Series 进行运算时，Pandas 会自动根据索引对齐数据，这使得数据处理更加高效。

我们可以使用 Pandas 库来创建一个 Series 对象，并且可以为其指定索引（`Index`）、名称（`Name`）以及值（`Values`）：

In [12]:
import pandas as pd

series = pd.Series([0, 1, 2, 3], name='A')

display(series)

# 显式设置索引
custom_index = [1, 2, 3, 4]  # 自定义索引
series_with_index = pd.Series([0, 1, 2, 3], index=custom_index, name='A')

display(series_with_index)

0    0
1    1
2    2
3    3
Name: A, dtype: int64

1    0
2    1
3    2
4    3
Name: A, dtype: int64

**输出最左边一列为index，第二列为value，下面是名称(Name)和数据类型(dtype)**

### 创建`Series`

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

参数说明：

`data`：Series 的数据部分，可以是**列表**、**数组**、**字典**、**标量值**等。如果不提供此参数，则创建一个空的 Series。

`index`：Series 的索引部分，用于对数据进行标记。可以是列表、数组、索引对象等。如果不提供此参数，则创建一个默认的整数索引。

`dtype`：指定 Series 的数据类型。可以是 NumPy 的数据类型，例如 `np.int64`、`np.float64` 等。如果不提供此参数，则根据数据自动推断数据类型。

`name`：Series 的名称，用于标识 Series 对象。如果提供了此参数，则创建的 Series 对象将具有指定的名称。

`copy`：是否复制数据。默认为 False，表示不复制数据。如果设置为 True，则复制输入的数据。

`fastpath`：是否启用快速路径。默认为 False。启用快速路径可能会在某些情况下提高性能。

## Series 方法

| 方法名称              | 功能描述                                                 |
| --------------------- | -------------------------------------------------------- |
| index                 | 获取 Series 的索引                                       |
| values                | 获取 Series 的数据部分（返回 NumPy 数组）                |
| head(n)               | 返回 Series 的前 n 行（默认为 5）                        |
| tail(n)               | 返回 Series 的后 n 行（默认为 5）                        |
| dtype                 | 返回 Series 中数据的类型                                 |
| notnull()             | 返回一个布尔 Series，表示每个元素是否不是 NaN            |
| unique()              | 返回 Series 中的唯一值（去重）                           |
| value_counts()        | 返回 Series 中每个唯一值的出现次数                       |
| map(func)             | 将指定函数应用于 Series 中的每个元素                     |
| apply(func)           | 将指定函数应用于 Series 中的每个元素，常用于自定义操作   |
| astype(dtype)         | 将 Series 转换为指定的类型                               |
| sort_values()         | 对 Series 中的元素进行排序（按值排序）                   |
| sort_index()          | 对 Series 的索引进行排序                                 |
| dropna()              | 删除 Series 中的缺失值（NaN）                            |
| fillna(value)         | 填充 Series 中的缺失值（NaN）                            |
| replace(to_replace, value) | 替换 Series 中指定的值                         |
| cumsum()              | 返回 Series 的累计求和                                   |
| cumprod()             | 返回 Series 的累计乘积                                   |
| shift(periods)        | 将 Series 中的元素按指定的步数进行位移                   |
| rank()                | 返回 Series 中元素的排名                                 |
| corr(other)           | 计算 Series 与另一个 Series 的相关性（皮尔逊相关系数）   |
| cov(other)            | 计算 Series 与另一个 Series 的协方差                     |
| to_list()             | 将 Series 转换为 Python 列表                             |
| to_frame()            | 将 Series 转换为 DataFrame                               |
| iloc[]                | 通过位置索引来选择数据                                   |
| loc[]                 | 通过标签索引来选择数据                                   |

In [32]:
import pandas as pd

data = [1, 9, 2, 20, 21, 14]
index = ['a', 'b', 'c', 'd', 'e', 'f']
s = pd.Series(data, index=index)

display(s.index)
display(s.values)
display(s.dtype)
display(s.head(2))  # 前两行
value = s[2:4]  # 单个元素索引不推荐，未来警告，可以通过s.loc['col']或者s['col']
display(value)
display(s['d'])  # 用自定义索引索引元素

# 使用 map 函数将每个元素加倍
s_doubled = s.map(lambda x: x * 2)  # map将指定函数用于Series
display(s_doubled)
display(s * 2)  # 同上
# 计算累计和
cumsum_s = s.cumsum()
display(cumsum_s)

# 查找缺失值(本案例无缺失值，返回全为False)
display(s.isnull())

# 排序
sorted_s = s.sort_values()
display(sorted_s)

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

array([ 1,  9,  2, 20, 21, 14], dtype=int64)

dtype('int64')

a    1
b    9
dtype: int64

c     2
d    20
dtype: int64

20

a     2
b    18
c     4
d    40
e    42
f    28
dtype: int64

a     2
b    18
c     4
d    40
e    42
f    28
dtype: int64

a     1
b    10
c    12
d    32
e    53
f    67
dtype: int64

a    False
b    False
c    False
d    False
e    False
f    False
dtype: bool

a     1
c     2
b     9
f    14
d    20
e    21
dtype: int64

## Series 基本操作

1. 使用`[]`(list)、`np.array([])`(ndarray)、dic`{'key': 'value'}`创建`Series`
2. 获取值  
    (1) `series[1:b]`（切片，**单个元素不推荐**）  
    (2) `series['col']`, `series['col1', 'col2']`（返回索引标签为'col1'到'col2'的元素）
3. 赋值: `s['col'] = value`
4. 通过new_index增加新元素: `s['new col'] = value`
5. `del` 删除单个(不能多个)元素: `del s['col']`
6. `drop` 删除一个或多个索引，并返回一个新的 `Series`: s_dropped = s.drop(['col'])

In [38]:
import pandas as pd

data = [1, 9, 2, 20, 21, 14]
index = ['a', 'b', 'c', 'd', 'e', 'f']
s = pd.Series(data, index=index)

display(s[:3])  # 切片
s['c'] = 1  # 索引修改值
display(s)
s['1'] = 'a'  # 索引赋新值
display(s)
del s['e']  # 删除单个元素
display(s)
s_dropped = s.drop(['c', '1'])
display(s_dropped)

a    1
b    9
c    2
dtype: int64

a     1
b     9
c     1
d    20
e    21
f    14
dtype: int64

a     1
b     9
c     1
d    20
e    21
f    14
1     a
dtype: object

a     1
b     9
c     1
d    20
f    14
1     a
dtype: object

a     1
b     9
d    20
f    14
dtype: object

## Series 基本运算

1. **算术运算**：支持对`Series`直接`+ - * /`
2. **过滤**：`filtered_series = series[series > 2]`（实际先返回布尔索引，再通过布尔索引取值）
3. **数学函数**：可以`function(series)`(np的函数也可以对series使用)

## Series 计算统计数据

1. **和**: `s.sum()`
2. **均值**: `s.mean()`
3. **最大值**: `s.max()`
4. **最小值**: `s.min()`
5. **标准差**: `s.std()`

# Series 属性和方法

1. **获取索引**: `s.index`
2. **获取值**: `s.values`（返回ndarray数组）
3. **获取统计信息**: `s.describe()`
4. **获取最大最小值的索引**: `max_index=s.idxmax()`; `min_index=s.idxmin()`
5. **数据类型**: `s.dtype`
6. **形状**: `s.shape`
7. **元素个数**: `s.size`
8. **前几个元素**: `s.head(n)`（默认为5）
9. **后几个元素**: `s.tail(n)`（默认为5）
10. **求和**: `s.sum()`
11. **平均值**: `s.mean()`
12. **标准差**: `s.std()`
13. **最大最小值**: `s.max()` / `s.min()`
14. **转换数据类型**: `s = s.astype('float64')`
15. **过滤**: `print(s > 2)` 返回 bool Series，其中的元素值大于2

# 3. Pandas 数据结构 -- DataFrame

DataFrame 是 Pandas 中的另一个核心数据结构，类似于一个二维的表格或数据库中的数据表。

DataFrame 是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔型值）。

DataFrame 既有行索引也有列索引，它可以被看做由 Series 组成的字典（共同用一个索引）。

DataFrame 提供了各种功能来进行**数据访问**、**筛选**、**分割**、**合并**、**重塑**、**聚合**以及**转换**等操作。

DataFrame 是一个非常灵活且强大的数据结构，广泛用于数据分析、清洗、转换、可视化等任务。

### DataFrame 特点

1. **二维结构**： DataFrame 是一个二维表格，可以被看作是一个 Excel 电子表格或 SQL 表，具有行和列。可以将其视为多个 Series 对象组成的**字典**。

2. **列的数据类型**： 不同的列可以包含不同的数据类型，例如整数、浮点数、字符串或 Python 对象等。

3. **索引**：DataFrame 可以拥有行索引和列索引，类似于 Excel 中的行号和列标。

4. **大小可变**：可以添加和删除列，类似于 Python 中的***字典***。

5. ***自动对齐***：在进行算术运算或数据对齐操作时，DataFrame 会自动对齐索引。

6. **处理缺失数据**：DataFrame 可以包含缺失数据，Pandas 使用 NaN（Not a Number）来表示。

7. **数据操作**：支持数据**切片**、**索引**、**子集分割**等操作。

8. ***时间序列支持***：DataFrame 对***时间序列数据***有特别的支持，可以轻松地进行时间数据的切片、索引和操作。

9. **丰富的数据访问功能**：通过 `.loc`、`.iloc` 和 `.query()` 方法，可以灵活地访问和筛选数据。

10. **灵活的数据处理功能**：包括数据***合并***、***重塑***、***透视***、***分组***和***聚合***等。

11. ***数据可视化***：虽然 DataFrame 本身不是可视化工具，但它可以与 Matplotlib 或 Seaborn 等可视化库结合使用，进行数据可视化。

12. **高效的数据输入输出**：可以方便地读取和写入数据，支持多种格式，如 **CSV**、**Excel**、**SQL 数据库**和 **HDF5** 格式。

13. **描述性统计**：提供了一系列方法来计算描述性统计数据，如 .describe()、.mean()、.sum() 等。

14. **灵活的数据对齐和集成**：可以轻松地与其他 DataFrame 或 Series 对象进行**合并**、**连接**或**更新**操作。

15. ***转换功能***：可以对数据集中的值进行转换，例如使用 `.apply()` 方法应用自定义函数。

16. ***滚动窗口和时间序列分析***：支持对数据集进行滚动窗口统计和时间序列分析。

### DataFrame 构建方法

`pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)`

参数说明：

`data`：DataFrame 的数据部分，可以是字典、二维数组、Series、DataFrame 或其他可转换为 DataFrame 的对象。如果不提供此参数，则创建一个空的 DataFrame。

`index`：DataFrame 的 ***行索引*** ，用于标识每行数据。可以是列表、数组、索引对象等。如果不提供此参数，则创建一个默认的整数索引。

`columns`：DataFrame 的 ***列索引*** ，用于标识每列数据。可以是列表、数组、索引对象等。如果不提供此参数，则创建一个默认的整数索引。

`dtype`：指定 DataFrame 的数据类型。可以是 NumPy 的数据类型，例如 np.int64、np.float64 等。如果不提供此参数，则根据数据自动推断数据类型。

`copy`：是否复制数据。默认为 False，表示不复制数据。如果设置为 True，则复制输入的数据。

In [39]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)
# loc属性返回指定行的数据，注意：返回结果其实就是一个一列的 Pandas Series 数据。
display(df.loc[0])  # 返回第一行
display(df.loc[1])  # 返回第二行

calories    420
duration     50
Name: 0, dtype: int64

calories    380
duration     40
Name: 1, dtype: int64

In [40]:
display(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40

# DataFrame 方法

| 方法名称           | 功能描述                                                     |
| ------------------ | ------------------------------------------------------------ |
| head(n)            | 返回 DataFrame 的前 n 行数据（默认前 5 行）                  |
| tail(n)            | 返回 DataFrame 的后 n 行数据（默认后 5 行）                  |
| info()             | 显示 DataFrame 的简要信息，包括列名、数据类型、非空值数量等  |
| describe()         | 返回 DataFrame 数值列的统计信息，如均值、标准差、最小值等    |
| shape              | 返回 DataFrame 的行数和列数（行数, 列数）                    |
| columns            | 返回 DataFrame 的所有列名                                    |
| index              | 返回 DataFrame 的行索引                                      |
| dtypes             | 返回每一列的数值数据类型                                     |
| sort_values(by)    | 按照指定列排序                                               |
| sort_index()       | 按行索引排序                                                 |
| dropna()           | 删除含有缺失值（NaN）的行或列                                |
| fillna(value)      | 用指定的值填充缺失值                                         |
| isnull()           | 判断缺失值，返回一个布尔值 DataFrame                         |
| notnull()          | 判断非缺失值，返回一个布尔值 DataFrame                       |
| loc[]              | 按标签索引选择数据                                           |
| iloc[]             | 按位置索引选择数据                                           |
| at[]               | 访问 DataFrame 中单个元素（比 loc[] 更高效）                 |
| iat[]              | 访问 DataFrame 中单个元素（比 iloc[] 更高效）                |
| apply(func)        | 对 DataFrame 或 Series 应用一个函数                          |
| applymap(func)     | 对 DataFrame 的每个元素应用函数（仅对 DataFrame）            |
| groupby(by)        | 分组操作，用于按某一列分组进行汇总统计                       |
| pivot_table()      | 创建透视表                                                   |
| merge()            | 合并多个 DataFrame（类似 SQL 的 JOIN 操作）                  |
| concat()           | 按行或按列连接多个 DataFrame                                 |
| to_csv()           | 将 DataFrame 导出为 CSV 文件                                 |
| to_excel()         | 将 DataFrame 导出为 Excel 文件                               |
| to_json()          | 将 DataFrame 导出为 JSON 格式                                |
| to_sql()           | 将 DataFrame 导出为 SQL 数据库                               |
| query()            | 使用 SQL 风格的语法查询 DataFrame                            |
| duplicated()       | 返回布尔值 DataFrame，指示每行是否是重复的                   |
| drop_duplicates()  | 删除重复的行                                                 |
| set_index()        | 设置 DataFrame 的索引                                        |
| reset_index()      | 重置 DataFrame 的索引                                        |
| transpose()        | 转置 DataFrame（行列交换）                                   |

In [43]:
import pandas as pd

# 创建 DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)

# 查看 基本信息
display(df.info())
 
# 获取描述统计信息
display(df.describe())  # 不支持 "string" 的列

# 按年龄排序，sort_values默认升序，ascending=False降序排列
df_sorted = df.sort_values(by='Age', ascending=False)
display(df_sorted)

# 选择指定列
print(df[['Name', 'Age']])  # 双中括号[[]]

# 按索引选择行
display(df.iloc[1:3])  # 第二行到第三行(按位置),不包括索引为3的行

# 按标签选择行
display(df.loc[1:2])  # 选择第二到第三行(按标签)，包括标签为2的列

# 按分组统计(按城市分组，计算平均年龄)
display(df.groupby('City')['Age'].mean())  # 注意中括号和小括号的使用

# 处理缺失值
df['Age'] = df['Age'].fillna(30)

# 导出为 CSV 文件
df.to_csv('output.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

None

             Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

      Name  Age         City
3    David   40      Houston
2  Charlie   35      Chicago
1      Bob   30  Los Angeles
0    Alice   25     New York

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

City
Chicago        35.0
Houston        40.0
Los Angeles    30.0
New York       25.0
Name: Age, dtype: float64

### DataFrame 的创建

可通过 **字典** 、 **列表的列表** 、 **二维数组(ndarray)** 、 **Series** 创建

In [45]:
# 字典
import pandas as pd

df = pd.DataFrame({'Column1': [1, 2, 3], 'Column2': [4, 5, 6]})
df

   Column1  Column2
0        1        4
1        2        5
2        3        6

In [57]:
# 列表的列表
import pandas as pd

df = pd.DataFrame({'Column1': [1, 2, 3], 'Column2': [4, 5, 6]},
                  columns=['Column1', 'Column2', 'Column3'])
df

   Column1  Column2 Column3
0        1        4     NaN
1        2        5     NaN
2        3        6     NaN

In [51]:
# ndarray二维数组
import numpy as np

df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['A', 'B', 'C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [115]:
import pandas as pd

# 创建 Series 时直接指定索引
s1 = pd.Series(['Alice', 'Bob', 'Charlie', 'David'], index=['A', 'B', 'C', 'D'])
s2 = pd.Series([25, 35, 30, 15], index=['A', 'B', 'C', 'D'])
s3 = pd.Series(['New York', 'Los Angeles', 'Chicago', 'Beijing'], index=['A', 'B', 'C', 'D'])

# 用字典创建 DataFrame
df2 = pd.DataFrame({'Name': s1, 'Age': s2, 'City': s3})
display(df2)

      Name  Age         City
A    Alice   25     New York
B      Bob   35  Los Angeles
C  Charlie   30      Chicago
D    David   15      Beijing

In [69]:
import pandas as pd

s1 = pd.Series(['Alice', 'Bob', 'Charlie', 'David'])
s2 = pd.Series([25, 35, 30, 15])
s3 = pd.Series(['New York', 'Los Angeles', 'Chicago', 'Beijing'])

# 先不指定索引，用默认索引创建 DataFrame
df = pd.DataFrame({'Name': s1, 'Age': s2, 'City': s3})
# 再设置新索引
df = df.set_index(pd.Index(['A', 'B', 'C', 'D']))
display(df)

      Name  Age         City
A    Alice   25     New York
B      Bob   35  Los Angeles
C  Charlie   30      Chicago
D    David   15      Beijing

In [65]:
"""
下面全为NaN，必须逐个Series定义index或者先定义df，在使用df.set_index(pd.Index([]))
"""
# 用 Series 创建（使用字典指定列名columns）
s1 = pd.Series(['Alice', 'Bob', 'Charlie', 'David'])
s2 = pd.Series([25, 35, 30, 15])
s3 = pd.Series(['New York', 'Los Angeles', 'Chicago', 'Beijing'])

df = pd.DataFrame({'Name': s1, 'Age': s2, 'City': s3}, index=['A', 'B', 'C', 'D'])
df

  Name  Age City
A  NaN  NaN  NaN
B  NaN  NaN  NaN
C  NaN  NaN  NaN
D  NaN  NaN  NaN

### DataFrame 属性和方法

1. 形状：`df.shape`
2. 列名：`df.columns`
3. 行索引：`df.index`
4. 前几行: `df.head(n)`
5. 后几行: `df.tail()`
6. 数据信息: `df.info()`
7. 统计信息: `df.describe()`
8. 均值: `df.mean()`
9. 和: `df.sum()`

### 访问 DataFrame 元素

In [96]:
df

      Name  Age         City  salary
A    Alice   10     New York    1000
B      Bob   15  Los Angeles    2000
C  Charlie   12      Chicago    3000
D    David   90      Beijing     500
4        1    2            3       4

In [84]:
# 访问列
display(df['City'])  # 列名访问
display(df.City)  # 属性访问
"""
注意：
df.loc访问用列名(column_name)
df.iloc访问用索引(0, 1, 2,···)
"""
display(df.loc[:, 'City'])  # 行切片+列名
display(df.iloc[:, 0])  # 行、列索引，0代表第一列, iloc=index loc
# 访问行
display(df['City'][0:2])  # df['column_name'][index]
# 访问单个元素（先行后列）
display(df.loc['C', 'City'])  # 顺序不能交换df.loc['index', 'column']
display(df.loc['C', 'Age'])  # 行 不支持index索引，只能用行名
display(df.iloc[1, 2])

A       New York
B    Los Angeles
C        Chicago
D        Beijing
Name: City, dtype: object

A       New York
B    Los Angeles
C        Chicago
D        Beijing
Name: City, dtype: object

A       New York
B    Los Angeles
C        Chicago
D        Beijing
Name: City, dtype: object

A      Alice
B        Bob
C    Charlie
D      David
Name: Name, dtype: object

A       New York
B    Los Angeles
Name: City, dtype: object

'Chicago'

30

'Los Angeles'

### 修改 DataFrame(注意维数对应)

1. 修改列数据: `df['column'] = [element1, element2, ...]`
2. 添加新列: `df['new_column'] = [element1, element2, ...]`
3. 添加新行: `df.loc[new_index_name(number)] = [element1, element2, ...]`不能超出index_max+1,数据类型与同列元素不用匹配
4. 添加新行: `df = pd.concat([df, new_row], ignore_index=True)`
new_row = pd.DataFrame([[ele1, ele2,...]], columns=['col1', 'col2']) 对应的元素加入到对应的列名下(不用按顺序)

In [112]:
display(df)
df['Age'] = [10, 15, 12, 90]
display(df)
df['salary'] = [1000, 2000, 3000, 500]
display(df)
df.loc['哈哈'] = [1, 2, 3, 4]  # 不能超出index_max+1,数据类型与同列元素不用匹配
display(df)
new_row = pd.DataFrame([['math', 100, 'world', '1w']], columns=['Name', 'salary', 'City', 'Age'])
df = pd.concat([df, new_row], ignore_index=True)
df

      Name  Age         City
A    Alice   25     New York
B      Bob   35  Los Angeles
C  Charlie   30      Chicago
D    David   15      Beijing

      Name  Age         City
A    Alice   10     New York
B      Bob   15  Los Angeles
C  Charlie   12      Chicago
D    David   90      Beijing

      Name  Age         City  salary
A    Alice   10     New York    1000
B      Bob   15  Los Angeles    2000
C  Charlie   12      Chicago    3000
D    David   90      Beijing     500

       Name  Age         City  salary
A     Alice   10     New York    1000
B       Bob   15  Los Angeles    2000
C   Charlie   12      Chicago    3000
D     David   90      Beijing     500
哈哈        1    2            3       4

      Name Age         City  salary
0    Alice  10     New York    1000
1      Bob  15  Los Angeles    2000
2  Charlie  12      Chicago    3000
3    David  90      Beijing     500
4        1   2            3       4
5     math  1w        world     100

### DataFrame 删除元素

1. 删除列: `df_dropped = df.drop('column1', axis=1)`(不指定axis报错,且要指定对是row(axis=0默认)还是column(axis=1))
2. 删除行: `df_dropped = df.drop(index)`

In [118]:
df_dropped = df2.drop(['Name', 'Age'], axis=1)
df_dropped

          City
A     New York
B  Los Angeles
C      Chicago
D      Beijing

In [120]:
df_dropped2 = df2.drop('B')
df_dropped2

      Name  Age      City
A    Alice   25  New York
C  Charlie   30   Chicago
D    David   15   Beijing

### DataFrame 的索引操作

1. 重置索引: df_reset=`df.rest_index`(drop=True)  
***行索引*** 重置为默认的0，1···
2. 设置索引: df=`df.set_index(['column1', 'column2', ...], drop=False, inplace=False, append=False)`  
    []给 ***列索引*** 排序(实际结果是 **层级索引** )  
    drop=False: 保留索引列  
inplace=True: 原地修改
append=True
3. 布尔索引: `df[df['column1'] > 2]`

| 功能点      | `set_index`                                                                                                                                                                                            | `reset_index`                                                                                          |
| -------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------ |
| **作用**   | 把某列设置为索引                                                                                                                                                                                               | 把索引恢复为普通列                                                                                              |
| **常见场景** | 想用某列唯一标识行（如 ID、时间戳）                                                                                                                                                                                    | 想把索引还原成普通数据列（比如保存成 CSV/Excel 时）                                                                        |
| **参数**   | - `keys`: 列名或列表<br>- `drop`: 是否删除设为索引的列（默认 True）<br>- `inplace`: 是否原地修改<br>- `append`: 是否追加到现有索引形成多级索引                                                                                                 | - `drop`: 是否丢弃当前索引列（默认 False，索引会变成普通列）<br>- `inplace`: 是否原地修改<br>- `col_level` 和 `col_fill`: 针对多级列名的处理 |

In [121]:
df.reset_index(drop=True)

      Name  Age         City
0    Alice   25     New York
1      Bob   35  Los Angeles
2  Charlie   30      Chicago
3    David   15      Beijing

In [132]:
df11 = df.set_index(['Age', 'City'], append=True)
df11

                      Name
  Age City
A 25  New York       Alice
B 35  Los Angeles      Bob
C 30  Chicago      Charlie
D 15  Beijing        David

In [133]:
df[df['Age'] < 30]

    Name  Age      City
A  Alice   25  New York
D  David   15   Beijing

### DataFrame 数据类型处理

1. 查看数据类型: df`.dtypes` (加s)
2. 转换数据类型: df['column1'] = df['column1']`.astype`('float64')

### DataFrame 的合并与分割

1. ***合并*** : 使用 `concat` 或 `merge` 方法

```python
# 纵向合并(默认axis=0纵向合并)
pd.concat([df1, df2], ignore_index=True)
#如果两个 DataFrame 的行数不一致，concat 会将较短的 DataFrame 补齐为 NaN。
#不需要列的重叠（有值相同），只是将列拼接在一起。
```
```python
# 横向合并（保留两个df on=Column1列值相同的行）
pd.merge(df1, df2, on='Column1')  # 同名列Column1（也可以用left_on,right_on不同名）要有相同的 值
```
2. ***分割*** : 使用 `pivot` , `melt` 或 自定义函数
```python
# 长格式转宽格式
df_pivot = df.pivot(index='Column1', columns='Column2', values='Column3')
```
```python
# 宽格式转长格式
df_melt = df.melt(id_vars='Column1', value_vars=['Column2', 'Column3'])
```

In [149]:
import pandas as pd

df1 = pd.DataFrame({'Name': ['Alice', 'Bob', 'John'], 'Age': [20, 25, 30]}) # (3, 2)
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
})  # (4, 3)
df3 = pd.DataFrame({'subject': ['math', 'computer'], 'Age': [25, 20], 'weight': [70, 60]})  # (2, 3)
# 纵向合并
df_concat = pd.concat([df2, df3], axis=0, ignore_index=True)  # 拼接了 Age 列，其他不拼接, 不加ignore_index会保留原来两个df的index
display(df_concat)  # (4, 3)+(2, 3) = (6, 5),相同的列有相同值也不合并，而是叠加，行数等于二者 行数 相加，列数 3+3-1
# 横向合并
df_merge = pd.merge(df1, df3, on='Age')  # how='cross'笛卡尔积
display(df_merge)  # (3, 2)+(2, 3) = （2, 4）,所得 行数 就者短的来

      Name  Age         City   subject  weight
0    Alice   25     New York       NaN     NaN
1      Bob   30  Los Angeles       NaN     NaN
2  Charlie   35      Chicago       NaN     NaN
3    David   40      Houston       NaN     NaN
4      NaN   25          NaN      math    70.0
5      NaN   20          NaN  computer    60.0

    Name  Age   subject  weight
0  Alice   20  computer      60
1    Bob   25      math      70

In [152]:
data = {
  "mango": [420, 380, 390],
  "apple": [50, 40, 45],
  "pear": [1, 2, 3],
  "banana": [23, 45,56],
  "type":['Truck','Van','Tram']
}
df = pd.DataFrame(data)

display(df)

# 修改某一列特定几行元素的值
array = df.type.isin(['Truck','Tram'])
df.loc[array,'type'] = 'Car'

display(df)

   mango  apple  pear  banana   type
0    420     50     1      23  Truck
1    380     40     2      45    Van
2    390     45     3      56   Tram

   mango  apple  pear  banana type
0    420     50     1      23  Car
1    380     40     2      45  Van
2    390     45     3      56  Car

这两个方法 `pivot` 和 `melt` 是 **pandas** 中常用的用于 **数据格式转换** 的工具，分别用于 **长格式转宽格式** 和 **宽格式转长格式**。具体用法如下：

---

### 1. **长格式转宽格式**：`pivot`

**作用**：将数据从长格式转换成宽格式，即将某一列的多个不同值分列展示。

#### 用法：

```python
df_pivot = df.pivot(index='Column1', columns='Column2', values='Column3')
```

* **`index`**：要作为行索引的列。
* **`columns`**：要作为列索引的列。
* **`values`**：要填充的数值列，通常是你想要展示的数值。

#### 举个例子：

假设原始数据 `df` 如下：

| Column1 | Column2 | Column3 |
| ------- | ------- | ------- |
| A       | X       | 10      |
| A       | Y       | 15      |
| B       | X       | 20      |
| B       | Y       | 25      |

执行：

```python
df_pivot = df.pivot(index='Column1', columns='Column2', values='Column3')
print(df_pivot)
```

结果：

| Column2 | X  | Y  |
| ------- | -- | -- |
| Column1 |    |    |
| A       | 10 | 15 |
| B       | 20 | 25 |

**说明**：

* 将 `Column2` 中的 `X` 和 `Y` 成为列索引。
* `Column1` 成为行索引，`Column3` 的值填充进新的 DataFrame。

---

### 2. **宽格式转长格式**：`melt`

**作用**：将数据从宽格式转换成长格式，将多个列合并成两列：一列是变量名，另一列是对应的值。

#### 用法：

```python
df_melt = df.melt(id_vars='Column1', value_vars=['Column2', 'Column3'])
```

* **`id_vars`**：不需要变动的列，通常是作为标识的列。
* **`value_vars`**：需要合并的列。可以指定多个列，或者不指定时，自动使用剩余的列。

#### 举个例子：

假设原始数据 `df` 如下：

| Column1 | Column2 | Column3 |
| ------- | ------- | ------- |
| A       | 10      | 20      |
| B       | 15      | 25      |

执行：

```python
df_melt = df.melt(id_vars='Column1', value_vars=['Column2', 'Column3'])
print(df_melt)
```

结果：

| Column1 | variable | value |
| ------- | -------- | ----- |
| A       | Column2  | 10    |
| A       | Column3  | 20    |
| B       | Column2  | 15    |
| B       | Column3  | 25    |

**说明**：

* `Column1` 作为标识列（`id_vars`）。
* `Column2` 和 `Column3` 变成了名为 `variable` 和 `value` 的两列，分别存储列名和对应的值。

---

### 小结：

* **`pivot`**：从长格式数据 **转换成宽格式**，指定某列的不同值为新的列。
* **`melt`**：从宽格式数据 **转换成长格式**，将多个列合并成两列：一个列名和一个对应的值。

## pivot不能有重复值（不能聚合）, 而 pivot_table 可以有（可以聚合）

In [165]:
import pandas as pd

# 创建 Series 时直接指定索引
s1 = pd.Series(['Alice', 'Bob', 'Charlie', 'David'], index=['A', 'B', 'C', 'D'])
s2 = pd.Series([25, 35, 30, 15], index=['0', '1', '2', '3'])
s3 = pd.Series(['New York', 'Los Angeles', 'Chicago', 'Beijing'], index=['0', '1', '2', '3'])

# 用字典创建 DataFrame
df = pd.DataFrame({'Name': s1, 'Age': s2, 'City': s3})
display(df)

      Name   Age         City
0      NaN  25.0     New York
1      NaN  35.0  Los Angeles
2      NaN  30.0      Chicago
3      NaN  15.0      Beijing
A    Alice   NaN          NaN
B      Bob   NaN          NaN
C  Charlie   NaN          NaN
D    David   NaN          NaN

In [168]:
import pandas as pd

# 创建 Series 时直接指定索引
s1 = pd.Series(['Alice', 'Bob', 'Charlie', 'David'], index=[0, 1, 2, 3])
s2 = pd.Series([25, 35, 30, 15], index=[0, 1, 2, 3])
s3 = pd.Series(['New York', 'Los Angeles', 'Chicago', 'Beijing'], index=[0, 1, 2, 3])

# 用字典创建 DataFrame
df = pd.DataFrame({'Name': s1, 'Age': s2, 'City': s3})
display(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   35  Los Angeles
2  Charlie   30      Chicago
3    David   15      Beijing

In [171]:
# 索引和切片
display(df[['Name', 'Age']])  # 提取多列
display(df[1:3])               # 切片行
display(df.loc[:, 'Name'])     # 提取单列
display(df.loc[1:2, ['Name', 'Age']])  # （行索引是非整数类型报错）标签索引提取指定行列
display(df.iloc[:, 1:])        # 位置索引提取指定列

      Name  Age
0    Alice   25
1      Bob   35
2  Charlie   30
3    David   15

      Name  Age         City
1      Bob   35  Los Angeles
2  Charlie   30      Chicago

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

      Name  Age
1      Bob   35
2  Charlie   30

   Age         City
0   25     New York
1   35  Los Angeles
2   30      Chicago
3   15      Beijing