# Pandas 数据处理

***数据清洗*** 与 ***预处理*** 常见步骤：

1. ***缺失值处理*** ：识别并填补缺失值，或删除含缺失值的行/列

2. ***重复数据处理*** ：检查并删除重复数据，确保每条数据唯一

3. ***异常值处理*** ：识别并处理异常值。如极端值、错误值

4. ***数据格式转换*** ：转换数据类型或进行单位转换，如日期格式转换

5. ***标准化与归一化*** ：对数值型数据进行标准化(`sklearn.process.Z-score`)或归一化(`Min-Max`)

6. ***类别数据编码*** ：将类别变量转换为数值形式，常见方法包括 `One-Hot`编码(独热编码)和标签编码

7. ***文本处理*** ：对文本数据进行清洗，如取出停用词、词干化、分词等

8. ***数据抽样*** ：从数据集中抽取样本，或通过采样/欠采样处理类别不平衡

9. ***特征工程*** ：创建新特征、删除不相关特征、选择重要特征等

![缺失数据](数据.png)

上表包含四种空数据 ：

1. `NaN`
2. `NA`(被识别为NaN)
3. `na`(需手动处理)
4. `--`(需手动处理)

| 标识       | 常见场景                                  | 典型工具/来源                          | 特点                                  |
|------------|-------------------------------------------|----------------------------------------|---------------------------------------|
| `NA`       | 统计、编程工具的“标准缺失值标识”          | Pandas、R 语言、SQL、Excel             | 最通用的“缺失值符号”，工具通常会自动识别（如 Pandas 中 `pd.isna()` 可检测）。 |
| `n/a`      | 日常表格、报告中的“无数据”标注            | Excel、CSV 文件、手动录入表格          | 是“Not Applicable”（不适用）或“Not Available”（不可用）的缩写，偏口语化/文档化。 |
| `—`（破折号） | 文本格式表格、可视化报表的“空白占位符”    | Excel 表格、Markdown 文档、数据看板    | 纯视觉符号，无实际语义，仅为了表格排版美观（需手动转换为标准缺失值才能处理）。 |
| `na`       | 小写形式，多为“人为录入不规范”导致        | 手动填写的 CSV、Excel 原始数据         | 和 `NA` 含义完全一致，仅大小写差异（工具通常也能识别，如 Pandas 对 `na` 和 `NA` 无区别）。 |

### 1. Pandas 清洗空值

1. `pd.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)`

参数说明：

`axis`：默认为 0，表示逢空值剔除整行，如果设置参数 axis＝1 表示逢空值去掉整列。  
`how`：默认为 'any' 如果一行（或一列）里任何一个数据有出现 NA 就去掉整行，如果设置 how='all' 一行（或列）都是 NA 才去掉这整行。  
`thresh`：设置需要多少非空值的数据才可以保留下来的。  
`subset`：设置想要检查的列。如果是多个列，可以使用列名的 list 作为参数。  
`inplace`：如果设置 True，将计算得到的值直接覆盖之前的值并返回 None，修改的是源数据。

2. `df.isnull()` : 判断各个单元格是否为空
3. `df.fillna({'col' :value(mean,median,mode)}, inplace=True)` : 替换空字段

In [9]:
import pandas as pd

df = pd.read_csv("property-data.csv")

# display(df['NUM_BEDROOMS'])
# display(df['NUM_BEDROOMS'].isnull())  # 认为NaN为空，na不认为为空

# 去除含NaN的行
# new_df = df.dropna()  # 返回一个DataFrame,要修改源数据(inplace=True)
# display(new_df)

# 去除某列字段值为空的行(也是删除整行)
# df1 = df.dropna(subset=['ST_NUM'])
# display(df1)

# 替换所有空字段
# df2 = df.fillna(12345)  # float
# display(df2)

# 替换PID列的空数据
# df3 = df['PID'].fillna(1235)
# display(df3)
# display(df)

0    100001000.0
1    100002000.0
2    100003000.0
3    100004000.0
4         1235.0
5    100006000.0
6    100007000.0
7    100008000.0
8    100009000.0
Name: PID, dtype: float64

           PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [17]:
# 实际替换单元格常常用该列的均值、中位数、众数替换
df = pd.read_csv("property-data.csv")
display(df)
# 均值替换 df['col'].mean()
# mean = df['ST_NUM'].mean()
# df.fillna({'ST_NUM': mean}, inplace=True)  # 源数据上修改
# display(df)

# 中位数替换df['col'].median()
# median = df['ST_NUM'].median()
# df.fillna({'ST_NUM' :median}, inplace=True)
# display(df)

# 众数替换 df['col'].mode()
mode = df['ST_NUM'].mode()
df.fillna({'ST_NUM':mode}, inplace=True)
display(df)

           PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

           PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0   201.0   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0   215.0  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

### Pandas 清洗重复数据

`df.duplicated()` 和 `df.drop_duplicates()` 方法

`df.duplicated()` 返回布尔值(第一个值返回True，之后的重复值False)

In [25]:
person = {
  "name": ['Google', 'Runoob', 'Runoob', 'Taobao'],
  "age": [50, 40, 40, 23]  
}
df = pd.DataFrame(person)
display(df)
display(df.duplicated())
df.drop_duplicates(inplace=True)
display(df)

     name  age
0  Google   50
1  Runoob   40
2  Runoob   40
3  Taobao   23

0    False
1    False
2     True
3    False
dtype: bool

     name  age
0  Google   50
1  Runoob   40
3  Taobao   23

### Pandas 清洗错误数据

`df.loc[index, 'col'] = value` (单个值处理)

`df.drop(index, inplace=True)` (删除含错误值的行)

`df.replace(old_value, new_value)` : 将指定值替换为新值

In [22]:
person = {
  "name": ['Google', 'Runoob' , 'Taobao'],
  "age": [50, 40, 12345]    # 12345 年龄数据是错误的
}

df = pd.DataFrame(person)
display(df)
# 错误值（单个）处理
df.loc[2, 'age'] = 30
display(df)

# 删除含错误值的行
for x in df.index:
    if df.loc[x, 'age'] > 120:
        df.drop(x, inplace=True)
display(df)

# 极端值处理
for x in df.index:
    if df.loc[x, 'age'] > 120:
        df.loc[x, 'age'] = 120
display(df)

     name    age
0  Google     50
1  Runoob     40
2  Taobao  12345

     name  age
0  Google   50
1  Runoob   40

     name  age
0  Google   50
1  Runoob   40

### Pandas 清洗格式错误数据

示例: 格式化日期

In [27]:
# 第三个日期格式错误
data = {
  "Date": ['2020/12/01', '2020/12/02' , '20201226'],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
display(df)

df['Date'] = pd.to_datetime(df['Date'], format='mixed')
display(df)

            Date  duration
day1  2020/12/01        50
day2  2020/12/02        40
day3    20201226        45

           Date  duration
day1 2020-12-01        50
day2 2020-12-02        40
day3 2020-12-26        45

### 常用方法及说明
数据清洗与预处理的常见方法：

| 操作        | 方法步骤                   | 说明                                           | 常用函数/方法                                          |
|-----------|------------------------|----------------------------------------------|--------------------------------------------------|
| 缺失值处理     | 填充缺失值                  | 使用指定的值（如均值、中位数、众数等）填充缺失值。                    | `df.fillna(value)`                               |
|           | 删除缺失值                  | 删除包含缺失值的行或列。                                 | `df.dropna()`                                    |
| 重复数据处理    | 删除重复数据                 | 删除 DataFrame 中的重复行                           | `df.drop_duplicates()`                           |
| 异常值处理     | 删除异常值（基于统计方法）          | 删除异常值。                                       | 自定义函数(如基于 `Z-score` 或`IQR`)                      |
|           | 替换异常值                  | 使用合适的值（如均值或中位数）替换异常值。                        | 自定义函数（如替换异常值）                                    |
| 数据格式转换    | 转换数据类型                 | 将数据类型从一个类型转换为另一个类型，如将字符串转换为日期。               | `df.astype()`                                    |
|           | 日期时间格式转换               | 转换字符串或数字为日期时间类型。                             | `pd.to_datetime()`                               |
| 标准化与归一化   | 标准化                    | 将数据转换为均值为0，标准差为1的分布。                         | `StandardScaler()`                               |
|           | 归一化                    | 将数据缩放到指定的范围（如[0, 1]）。                        | `MinMaxScaler()`                                 |
| 类别数据编码    | 标签编码                   | 将类别变量转换为整数形式。                                | `LabelEncoder()`                                 |
|           | 独热编码（One-Hot Encoding） | 将每个类别转换为一个新的二进制特征。                           | `pd.get_dummies()`                               |
| 文本数据处理    | 去除停用词                  | 从文本中去除无关紧要的词，如 "the"、"is" 等。                 | 自定义函数（基于 nltk 或 spaCy）                           |
|           | 词干化与词形还原               | 提取词干或恢复单词的基本形式。                              | `nltk.stem.PorterStemmer()`                      |
|           | 分词                     | 将文本分割成单词或子词。                                 | `nltk.word_tokenize()`                           |
| 数据抽样      | 随机抽样                   | 从数据中随机抽取一定比例的样本。                             | `df.sample()`                                    |
|           | 上采样和下采样                | 通过过采样（复制少数类样本）或欠采样（减少多数类样本）来平衡数据集中的类别分布      | `SMOTE()`(上采样); `RandomUnderSampler()`(下采样)        |
| 特征工程      | 特征选择                   | 选择对目标变量有影响的特征，去除冗余或无关特征。                     | `SelectKBest()`                                  |
|           | 特征提取                   | 从原始数据中创建新的特征，提升模型的预测能力。                      | `PolynomialFeatures()`                           |
|           | 特征缩放                   | 对数值特征进行缩放，使其具有相同的量级。                         | `MinMaxScaler()`、`StandardScaler()`              |
| 类别特征映射    | 特征映射                   | 将类别变量映射为对应的数字编码。                             | 自定义映射函数                                          |
| 数据合并与连接   | 合并数据                   | 将多个 DataFrame 按照某些列合并在一起，支持内连接、外连接、左连接、右连接等。 | `pd.merge()`                                     |
|           | 连接数据                   | 将多个 DataFrame 进行行或列拼接。                       | `pd.concat()`                                    |
| 数据重塑      | 数据透视表                  | 将数据根据某些维度进行分组并计算聚合结果。                        | `pd.pivot_table()`                               |
|           | 数据变形                   | 改变数据的形状，如从长格式转为宽格式或从宽格式转为长格式。                | `df.melt()`、`df.pivot()`                         |
| 数据类型转换与处理 | 字符串处理                  | 对字符串数据进行处理，如去除空格、转换大小写等。                     | `str.replace()`、`str.upper()` 等                  |
|           | 分组计算                   | 按照某个特征分组后进行聚合计算。                             | `df.groupby()`                                   |
| 缺失值预测填充   | 使用模型预测填充缺失值            | 使用机器学习模型（如回归模型）预测缺失值，并填充缺失数据。                | 自定义模型（如 `sklearn.linear_model.LinearRegression`） |
| 时间序列处理    | 时间序列缺失值填充              | 使用时间序列的方法（如前向填充、后向填充）填充缺失值。                  | `df.fillna(method='ffill')`                      |
|           | 滚动窗口计算                 | 使用滑动窗口进行时间序列数据的统计计算（如均值、标准差等）。               | `df.rolling(window=5).mean()`                    |
| 数据转换与映射   | 数据映射与替换                | 将数据中的某些值替换为其他值。                              | `df.replace()`                                   |

以下是你提到的这些数据预处理和特征工程相关方法的详细讲解：

### 1. Z-score（标准化）(scipy.stats.zscore()或sklearn.preprocessing)
- **原理**：将数据转换为均值为0、标准差为1的分布，公式为 `z = (x - μ) / σ`，其中μ是均值，σ是标准差
- **用途**：消除不同特征的量纲影响，使数据处于同一量级，适用于近似正态分布的数据
- **适用场景**：SVM、线性回归等对特征尺度敏感的算法

### 2. IQR（四分位距）(pandas.Series.quantile()用于计算四分位数)
- **原理**：第75百分位数与第25百分位数的差值（IQR = Q3 - Q1）
- **用途**：主要用于异常值检测，通常将小于Q1-1.5×IQR或大于Q3+1.5×IQR的值视为异常值
- **优点**：对异常值不敏感，比均值和标准差更稳健

### 3. StandardScaler()(sklearn.preprocessing)
- **原理**：sklearn中的标准化工具，本质上实现Z-score标准化
- **特点**：
  - 计算训练集的均值和标准差用于缩放数据
  - 保持数据的分布形状，使各特征具有相同的方差
- **使用示例**：
```python
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
```

### 4. MinMaxScaler()(sklearn.preprocessing)
- **原理**：将数据缩放到[0,1]区间，公式为 `X_scaled = (X - X.min) / (X.max - X.min)`
- **特点**：
  - 会受到异常值的影响
  - 适用于分布较为均匀的数据
- **用途**：当需要将特征压缩到特定范围时使用，如神经网络的输入层

### 5. LabelEncoder()(sklearn.preprocessing)
- **原理**：将类别特征转换为0到n_classes-1的整数
- **适用场景**：处理有序类别特征（如学历：高中=0，本科=1，硕士=2）
- **注意**：不适合无序类别特征，会引入不必要的顺序关系
- **使用示例**：
```python
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoded_labels = encoder.fit_transform(categorical_data)
```

### 6. pd.get_dummies()
- **原理**：对类别特征进行独热编码，为每个类别创建一个二进制列
- **适用场景**：处理无序类别特征（如颜色：红、绿、蓝）
- **特点**：
  - 不会引入顺序关系
  - 可能导致维度灾难（高基数特征）
- **使用示例**：
```python
import pandas as pd
encoded_data = pd.get_dummies(data, columns=['categorical_column'])
```

### 7. nltk.stem.PorterStemmer()(nltk.tem)
- **原理**：Porter词干提取算法，将单词还原为其词干形式
- **用途**：自然语言处理中减少词汇量，将不同形式的同一词归一化
- **示例**："running" → "run"，"flies" → "fli"
- **使用示例**：
```python
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
stemmed_word = stemmer.stem("running")  # 结果为 "run"
```

### 8. nltk.word_tokenize()(nltk.tokenize)
- **原理**：将文本分割为单词或子词（tokens）的过程
- **用途**：NLP预处理的基础步骤，将连续文本转换为离散单元以便后续处理
- **示例**："I love NLP!" → ["I", "love", "NLP", "!"]
- **使用示例**：
```python
from nltk.tokenize import word_tokenize
tokens = word_tokenize("Hello world!")  # 结果为 ["Hello", "world", "!"]
```

### 9. SMOTE()（上采样）(imblearn.over_sampling)
- **原理**：合成少数类样本的过采样技术，通过在少数类样本之间插值生成新样本
- **用途**：解决类别不平衡问题
- **优点**：不会导致过拟合（相比简单复制样本）
- **使用示例**：
```python
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
```

### 10. RandomUnderSampler()（下采样）(imblearn.under_sampling)
- **原理**：随机删除多数类样本，使各类别样本数量接近
- **用途**：解决类别不平衡问题
- **注意**：可能会丢失多数类中的重要信息
- **适用场景**：多数类样本量极大的情况

### 11. SelectKBest()(sklearn.feature_selection)
- **原理**：根据统计测试选择k个最佳特征
- **常用评分函数**：
  - 分类问题：卡方检验、互信息
  - 回归问题：皮尔逊相关系数、互信息
- **用途**：特征选择，减少维度，提高模型效率
- **使用示例**：
```python
from sklearn.feature_selection import SelectKBest, chi2
selector = SelectKBest(chi2, k=10)
X_new = selector.fit_transform(X, y)
```

### 12. PolynomialFeatures()(sklearn.preprocessing)
- **原理**：生成特征的多项式组合和交互项
- **参数**：degree指定多项式阶数
- **示例**：degree=2时，特征[x1, x2]会生成[x1, x2, x1², x2², x1x2]
- **用途**：捕捉特征之间的非线性关系和交互效应
- **注意**：可能导致维度爆炸，通常配合正则化使用

这些方法在机器学习 pipeline 中经常组合使用，根据具体数据特点和任务需求选择合适的预处理方法是构建高性能模型的关键步骤。

In [28]:
# 独热编码(相当于向量表示类别)
data = {'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}

df = pd.DataFrame(data)
display(df)
# 对 “City” 列进行 One-Hot 编码
df_encoded = pd.get_dummies(df, columns=['City'])
display(df_encoded)

          City
0     New York
1  Los Angeles
2      Chicago
3      Houston

   City_Chicago  City_Houston  City_Los Angeles  City_New York
0         False         False             False           True
1         False         False              True          False
2          True         False             False          False
3         False          True             False          False

In [31]:
# 标准化
from sklearn.preprocessing import StandardScaler

data = {'Age': [25, 30, 35, 40, 45],
        'Salary': [50000, 60000, 70000, 80000, 90000]}

df = pd.DataFrame(data)
display(df)
# 标准化数据
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)  # 返回ndarray
print(df_scaled)

   Age  Salary
0   25   50000
1   30   60000
2   35   70000
3   40   80000
4   45   90000

[[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]